### ISSUE TITLE
[MMISI] #2 The blog pages aren't available...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#29]
The blog pages aren't available to review

*Source url:* https://mmisi-frontend.netlify.app/claims.html#
*Reported by:* 
*Reported at:* 31 May at 18:02 UTC

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 100.0

*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1486x723

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/6r09gff444hbct71r59z/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQwMjAxNjUsImRhdGEiOnsicmVwb3J0IjoiNnIwOWdmZjQ0NGhiY3Q3MXI1OXoiLCJ1c2VyIjoiR2l0SHViIn19.mt1B2b_Rc0MVSiOBJp1CWUGDYA3EK-qS3_9BXVK1KbE)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/6r09gff444hbct71r59z](https://ybug.io/dashboard/reports/detail/6r09gff444hbct71r59z)

**Comment by webrgp** [comment]
- [ ] Create blog listing page 
- [ ] Create blog detail page

Both from Figma file.

**Comment by diegocosta-dev** [comment]
> 

I gonna do this one!

**Comment by diegocosta-dev** [comment]
> * [ ]  Create blog listing page
> * [ ]  Create blog detail page
> 
> Both from Figma file.

I gonna do this one!
