### ISSUE TITLE
[MMISI] #3 On mobile, let's swap the...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#30]
On mobile, let's swap the profile card with a horizontal-style card. I've added a variant to the component in Figma

*Source url:* https://mmisi-frontend.netlify.app/who-we-are.html
*Reported by:* 
*Reported at:* 31 May at 18:24 UTC

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 100.0

*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1486x723

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/vn0bzcj0vvcx61py7jj4/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQwMjE0OTYsImRhdGEiOnsicmVwb3J0Ijoidm4wYnpjajB2dmN4NjFweTdqajQiLCJ1c2VyIjoiR2l0SHViIn19.Ao8ujkZoVDcyBqTbkQtQzjQ_KzuMoqgWdfCYTJvmmdk)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/vn0bzcj0vvcx61py7jj4](https://ybug.io/dashboard/reports/detail/vn0bzcj0vvcx61py7jj4)

**Comment by NovaDrake76** [comment]
> @NovaDrake76 Make the change for mobile only.

Like this (width 350px, following figma componet design)?
![image](https://user-images.githubusercontent.com/65428910/171749481-c92155b8-0124-4891-8da3-936fdda28567.png)

Or this? (width full, following page padding)
![image](https://user-images.githubusercontent.com/65428910/171750096-8dc9b2f3-1f35-4fae-b038-b4c85c885fb3.png)

**Comment by webrgp** [comment]
I like the first one, with max width at 350px, centered.

**Comment by webrgp** [comment]
Make sure the grid fill the narrow container. Add `sm:w-full` to the grid container.
