### ISSUE TITLE
[MMISI] #5 New London County Mutual card...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#32]
New London County Mutual card not rendering

*Source url:* https://mmisi-frontend.netlify.app/claims.html
*Reported by:* nathan.marques176@gmail.com
*Reported at:* 31 May at 20:53 UTC

*Location:* BR, Rio Grande do Norte, Natal
*Browser:* Chrome 101.0.4951.67

*OS:* Windows 10.0
*Screen:* 1920x1080
*Viewport:* 1920x1007

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/fgd4cg5f7qm1zs1ntqdn/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQwMzA0MzAsImRhdGEiOnsicmVwb3J0IjoiZmdkNGNnNWY3cW0xenMxbnRxZG4iLCJ1c2VyIjoiR2l0SHViIn19.ONS9uETBatTqVVIIhZvTNIT53DCfcPnnukKmtUSlLJY)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/fgd4cg5f7qm1zs1ntqdn](https://ybug.io/dashboard/reports/detail/fgd4cg5f7qm1zs1ntqdn)

**Comment by NovaDrake76** [comment]
How should be:
![image](https://user-images.githubusercontent.com/65428910/171283002-dcbfb18b-c28a-4ee9-befb-73753a718c7e.png)

**Comment by NovaDrake76** [comment]
Actually messed up Payments with Claims, sorry.

**Comment by webrgp** [comment]
Same as https://github.com/dative/mmisi-frontend/issues/41
