### ISSUE TITLE
[MMISI] #6 Header not positioned correctly...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#33]
Header not positioned correctly at ~320px width devices

*Source url:* https://mmisi-frontend.netlify.app/
*Reported by:* nathan.marques176@gmail.com
*Reported at:* 31 May at 21:10 UTC

*Location:* BR, Rio Grande do Norte, Natal
*Browser:* Firefox 100.0

*OS:* Windows 10.0
*Screen:* 320x535
*Viewport:* 320x535

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/w36q8spj4wpkh3r20d7k/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQwMzE0MzcsImRhdGEiOnsicmVwb3J0IjoidzM2cThzcGo0d3BraDNyMjBkN2siLCJ1c2VyIjoiR2l0SHViIn19.37plUi3phxvz1Spskuk7TjGjvTjxjli1Xrf8s04bQWI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/w36q8spj4wpkh3r20d7k](https://ybug.io/dashboard/reports/detail/w36q8spj4wpkh3r20d7k)

**Comment by NovaDrake76** [comment]
cut content at ~310px width devices
![image](https://user-images.githubusercontent.com/65428910/171285379-94ca17fd-cb70-4ab7-a2e6-9c5f2e5654cc.png)

**Comment by diegocosta-dev** [comment]
I think it's correct! was made to have a horizontal scroll bar, when new links can be added later.

**Comment by webrgp** [comment]
Thanks @NovaDrake76! @diegocosta-dev is right, about the meta nav, but more important is that the minimum mobile size accepted is 360px wide.
