### ISSUE TITLE
[MMISI] #14 Text in input should be in a...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#42]
Text in input should be in a placeholder.

*Source url:* https://mmisi-frontend.netlify.app/contact.html
*Reported by:* nathan.marques176@gmail.com
*Reported at:* 01 Jun at 21:47 UTC

*Location:* BR, Rio Grande do Norte, Natal
*Browser:* Firefox 100.0

*OS:* Windows 10.0
*Screen:* 358x642
*Viewport:* 358x642

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/pt6mzmpgk37h8bck3bx2/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQxMjAwMzMsImRhdGEiOnsicmVwb3J0IjoicHQ2bXptcGdrMzdoOGJjazNieDIiLCJ1c2VyIjoiR2l0SHViIn19.7jHrmL5TrEvED34rrPjzqI6Ket75NOXHFq-wyy497sE)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/pt6mzmpgk37h8bck3bx2](https://ybug.io/dashboard/reports/detail/pt6mzmpgk37h8bck3bx2)

**Comment by NovaDrake76** [comment]
Also, "Send" button looks better if centered (in mobile).

**Comment by webrgp** [comment]
Values in field are there to demonstrate select color.
