### ISSUE TITLE
[MMISI] #15 Make blog detail page container...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#43]
Make blog detail page container the same width as rest of the pages

*Source url:* https://mmisi-frontend.netlify.app/blog-detail.html
*Reported by:* 
*Reported at:* 02 Jun at 13:54 UTC

*Location:* US, Massachusetts, Buzzards Bay
*Browser:* Firefox 101.0

*OS:* macOS 10.15
*Screen:* 2560x1440
*Viewport:* 1398x753

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/87c23pkqpahm15g0wwg1/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQxNzgwNTksImRhdGEiOnsicmVwb3J0IjoiODdjMjNwa3FwYWhtMTVnMHd3ZzEiLCJ1c2VyIjoiR2l0SHViIn19.-xR91lqCc0FMl97Ifk30qUb5vUWowC-0ia4lklvp1p0)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/87c23pkqpahm15g0wwg1](https://ybug.io/dashboard/reports/detail/87c23pkqpahm15g0wwg1)

**Comment by webrgp** [comment]
It matches the Figma file. Are you sure?

![Screen Shot 2022-06-02 at 10 05 48 AM](https://user-images.githubusercontent.com/994788/171647958-9aaa4afd-04c5-4e22-86d0-630e3cdffe66.png)

**Comment by chrisobs13** [comment]
Yes you and I had decided to make it the same width for consistency like with the privacy policy page

**Comment by webrgp** [comment]
Got it. @diegocosta-dev Make the page header container for the blog detail 1110px (narrow).
