### ISSUE TITLE
[MMISI] #18 The blog page image is not have a height limit

### ISSUE THREAD

**Issue by diegocosta-dev** [dative/mmisi-frontend#50]
If the user uploads the image that has different size is what will happen.
Need we to fix it?

![image](https://user-images.githubusercontent.com/48633894/171733252-63c85664-4b73-425a-bde8-8ae51c461ef7.png)

**Comment by diegocosta-dev** [comment]
The width is ok

![image](https://user-images.githubusercontent.com/48633894/171734339-1641865d-3b79-4ff5-ba95-270a822c6823.png)

**Comment by diegocosta-dev** [comment]
the same to blog cards

![image](https://user-images.githubusercontent.com/48633894/171737091-abe8bb81-7cfd-4695-ae6e-fa8197583090.png)

**Comment by webrgp** [comment]
Pictures will be cropped by the CMS
