### ISSUE TITLE
[MMISI] #25 Please add the flooded house...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#61]
Please add the flooded house stock photo. The one with the life raft in the kitchen.

*Source url:* https://mmisi-frontend.netlify.app/services.html
*Reported by:* 
*Reported at:* 29 Jun at 14:28 UTC

*Location:* US, Virginia
*Browser:* Chrome 103.0.0.0

*OS:* Windows 10.0
*Screen:* 1280x1024
*Viewport:* 1280x881

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/k4dtz3hpbtt2530q0bcb/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY1MTI4OTMsImRhdGEiOnsicmVwb3J0IjoiazRkdHozaHBidHQyNTMwcTBiY2IiLCJ1c2VyIjoiR2l0SHViIn19.QCzpy3tU-45UAKUACs7CJOLpO8RfluLTUuZ6T29zeA8)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/k4dtz3hpbtt2530q0bcb](https://ybug.io/dashboard/reports/detail/k4dtz3hpbtt2530q0bcb)

**Comment by chrisobs13** [comment]
![our-services-murray-macdonald-insurance](https://user-images.githubusercontent.com/884088/178592383-39e8c800-2260-470c-85bb-53999b9e390e.jpg)
