### ISSUE TITLE
[MMISI] #26 Please add stock photo of the...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#62]
Please add stock photo of the girl in the car accident holding her neck.

*Source url:* https://mmisi-frontend.netlify.app/services.html
*Reported by:* 
*Reported at:* 29 Jun at 14:28 UTC

*Location:* US, Virginia
*Browser:* Chrome 103.0.0.0

*OS:* Windows 10.0
*Screen:* 1280x1024
*Viewport:* 1280x881

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/t5b2jcyjdx7t5jjj5qbn/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY1MTI5MzYsImRhdGEiOnsicmVwb3J0IjoidDViMmpjeWpkeDd0NWpqajVxYm4iLCJ1c2VyIjoiR2l0SHViIn19.MVIw1-yOKySfcIRbaD-bVdbpXxmD5AnW79_ZKWj8Rco)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/t5b2jcyjdx7t5jjj5qbn](https://ybug.io/dashboard/reports/detail/t5b2jcyjdx7t5jjj5qbn)

**Comment by chrisobs13** [comment]
![personal-insurance](https://user-images.githubusercontent.com/884088/178592501-61a3c3cb-a242-47e7-b814-eb1ebea9b9d8.jpg)
