### ISSUE TITLE
[MMISI] #27 Please add stock photo of...

### ISSUE THREAD

**Issue by webrgp** [dative/mmisi-frontend#63]
Please add stock photo of beached speedboat.

*Source url:* https://mmisi-frontend.netlify.app/services.html
*Reported by:* 
*Reported at:* 29 Jun at 14:30 UTC

*Location:* US, Virginia
*Browser:* Chrome 103.0.0.0

*OS:* Windows 10.0
*Screen:* 1280x1024
*Viewport:* 1280x881

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/90bg0g4hr4xzr0anq3gn/p8kc037bm9dbrx94dpgg/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTY1MTMwMzQsImRhdGEiOnsicmVwb3J0IjoicDhrYzAzN2JtOWRicng5NGRwZ2ciLCJ1c2VyIjoiR2l0SHViIn19.mC2D4Gy27vNCAZ6daKRaN1hyfYyvQJHWh019pGXsKWo)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/p8kc037bm9dbrx94dpgg](https://ybug.io/dashboard/reports/detail/p8kc037bm9dbrx94dpgg)

**Comment by chrisobs13** [comment]
![business-and-nonprofit-insurance-coverages](https://user-images.githubusercontent.com/884088/178592450-4f47f561-43df-4666-af25-f70f68b3ecce.jpg)
